### ISSUE TITLE
 Student names change problem 

### ISSUE THREAD

**Issue by karinakozarova** [pu6ki/elsyser-web-client#8]
After changing name in settings, it is not updated everywhere.
![31561481-af51861a-b060-11e7-81ed-e74fe7cec72b](https://user-images.githubusercontent.com/8996698/31578337-09f71266-b128-11e7-8f08-740d3d684a8a.jpg)
![31561486-b23f9c68-b060-11e7-90c7-94eaef967e73](https://user-images.githubusercontent.com/8996698/31578338-0a20403c-b128-11e7-8839-7cb321c17d2c.jpg)

**Comment by matir8** [comment]
Username is now updated on change. #7
